server {
    listen 80;
    server_name ns.parkly.pt 193.180.210.145;

    root /var/www/ns;
    index index.html;

    # PHP
    location ~ \.php$ {
        fastcgi_pass unix:/var/run/php/php8.3-fpm.sock;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    # PDF grande — aumentar timeout
    location ~* \.pdf$ {
        add_header Cache-Control "public, max-age=86400";
    }

    # Segurança — esconder ficheiros de config
    location ~ /\. {
        deny all;
    }
}
